config/routes.rb
Rails.application.routes.draw do

    root 'front_page#index'

    get '/fandom' => 'fandom#index', as: :fandoms
    get '/fandom/new' => 'fandom#new', as: :new_fandom

    get '/fandom/:id' => 'fandom#show', as: :fandom
    get '/fandom/:id/comments' => 'comments#show', as: :fandom_comments

    post '/fandom' => 'fandom#create'
    post '/fandom/:id/comments' => 'comments#create', as: :comment_section
    get '/fandom/:id/edit' => 'fandom#edit', as: :edit_fandom

    patch '/fandom/:id' => 'fandom#update'
    delete 'fandom/:id' => 'fandom#destroy'

    get 'login' => 'sessions#new', as: :login
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy', as: :logout

    get '/user' => 'user#index', as: :users
    get '/user/new' => 'user#new', as: :new_user
    get 'user/:id' => 'user#show', as: :user
    post '/user' => 'user#create'
    get '/user/:id/edit' => 'user#edit', as: :edit_user
    patch '/user/:id/edit' => 'user#update'
    delete 'user/:id' => 'user#destroy'


    get '/fandom_favorite/:id' => 'fandoms_user#create', as: :favorite
    get 'fandom_unfavorite/:id' => 'fandoms_user#destroy', as: :unfavorite
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :fandom
  belongs_to :user
end

app/models/fandom.rb
class Fandom < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :comments, :dependent => :destroy
end

app/models/fandoms_user.rb
class FandomsUser < ApplicationRecord
  belongs_to :fandom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_and_belongs_to_many :fandoms
  has_many :comments, :dependent => :destroy
  has_attached_file :user_image,
                    styles: { medium: "500x500#", thumb: "100x100#" },
                    storage: :s3,
                    url: ":s3_domain_url",
                    path: "/:user/:attachment/:id_partition/:style/:filename",
                    s3_region: ENV["S3_REGION"],
                    s3_credentials: Proc.new{ |a| a.instance.s3_credentials }
                    

    def s3_credentials
      {
        bucket: ENV["S3_BUCKET_NAME"],
        access_key_id: ENV["S3_ACCESS_KEY_ID"],
        secret_access_key: ENV["S3_SECRET_ACCESS_KEY"]
      }
    end
  validates_attachment_content_type :user_image, content_type: /\Aimage\/.*\Z/
  validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
      if @current_user
        return @current_user
    else
      return nil
    end
    end
  end

    def logged_in
      !!current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  end

  def create
    @fandom = Fandom.find(params[:id])
    @comment = @fandom.comments.create(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to fandom_path @fandom
  end


  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/fandom_controller.rb
class FandomController < ApplicationController
  def index
      @fandoms = Fandom.order('title ASC')
    end

    def show
        @fandom = Fandom.find(params[:id])
        @comment = Comment.new
    end

    def new
      @fandom = Fandom.new
    end

  def create
      @fandom = Fandom.new({
      title: params[:fandom][:title],
      source: params[:fandom][:source],
      description: params[:fandom][:description]
      })

        if @fandom.save
          redirect_to fandoms_path
        else
          redirect_to new_fandom_path
        end
      end

      def edit
        @fandom  = Fandom.find(params[:id])
        puts @fandom.inspect
      end

      def update
        puts params
        @fandom = Fandom.find(params[:id])
        @fandom.title = params[:fandom][:title]
        @fandom.source = params[:fandom][:source]
        @fandom.description = params[:fandom][:description]
        @fandom.save

        redirect_to fandom_path
      end

      def destroy
        @fandom = Fandom.find(params[:id])
        @fandom .destroy
        redirect_to fandoms_path
      end
    end

app/controllers/fandoms_user_controller.rb
class FandomsUserController < ApplicationController

  def create
    @fandom = Fandom.find(params[:id])
    current_user.fandoms << @fandom
    redirect_to user_path(current_user)
  end
  def destroy
    @fandom = Fandom.find(params[:id])
    current_user.fandoms.delete(@fandom)
    redirect_to fandom_path
  end
end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #first try to find user by email in the db
    @user = User.find_by_email(params[:login][:email])
    # if user does exist AND they put in the right password:
    if @user && @user.authenticate(params[:login][:password])
      #generate cookie for the user & redirect them
      session[:user_id] = @user.id
      redirect_to user_path(@user)
      flash[:notice] = "Welcome"
    else
      redirect_to login_path
      flash[:alert] = "Sorry, try again."
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logged out. Goodbye"
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authorize, only: [:show]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user.user_id = 0
    if @user.save
      @user.user_id = @user.id
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
      flash[:notice] = "Welcome"
    else
      redirect_to new_user_path
      flash[:alert] = "Sorry, try again."
    end
  end

  def edit
    @user  = User.find(params[:id])
    puts @user.inspect
  end

  def update
    puts params
    @user = User.find(params[:id])
    @user.name = params[:user][:name]
    @user.bio = params[:user][:bio]
    if params[:user][:user_image]
    @user.user_image = params[:user][:user_image]
  end
    @user.user_id = @user.id
    @user.save
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
    def user_params
        params.require(:user).permit(:name, :email, :password, :bio, :user_image)
    end

    def authorize
        redirect_to root_path unless logged_in
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fandom_helper.rb
module FandomHelper
end

app/helpers/front_page_helper.rb
module FrontPageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/fandom/create.html.erb
<h1>Fandom#create</h1>
<p>Find me in app/views/fandom/create.html.erb</p>

app/views/fandom/destroy.html.erb
<h1>Fandom#destroy</h1>
<p>Find me in app/views/fandom/destroy.html.erb</p>

app/views/fandom/edit.html.erb
<h1>Edit the Fandom!</h1>
<div class="input">
<%= form_for @fandom do |f| %>
  <%= f.text_field :title, placeholder: "Name" %>
  <%= f.text_field :source, placeholder: "Film/Show" %>
  <div class="edit-fandom">
    <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
    <%= f.submit class: "btn btn-info" %>
  </div>
<% end %>
</div>

app/views/fandom/index.html.erb
<h1>Fandoms</h1>
<p>Here is a list of all the fandoms we currently have. <br>
  If you have one you wish to add, feel free to. <br>
  Or, if there's something you wish to edit, feel free to do so as well.</p>

<ul id="list">
  <% @fandoms.each do |f| %>
<li style= "padding: 10px;"> <%= link_to(f.title, "/fandom/#{f.id}") %>
</li>
  <% end %>
</ul>
<p>
<%= link_to('Add New Fandom', new_fandom_path, class: "btn btn-info") %>
</p>
<p>
<%= link_to('Back to User', user_path(current_user), class: "btn btn-success") %>
</p>

app/views/fandom/new.html.erb
<h1>Add New</h1>
<div class="input">
<%= form_for @fandom do |n| %>
  <%= n.text_field :title, placeholder: "Title" %>
  <%= n.text_field :source, placeholder: "Film/Show" %>
  <div class="fandom-new ">
  <%= n.text_area :description, placeholder: "Description", class: "form-control" %>
  </div>
    <%= n.submit class: 'btn btn-info'%>
<% end %>
</div>

app/views/fandom/show.html.erb
<h1 class="fandom"><%= @fandom.title %></h1>

<h3 id="source">Source: <%= @fandom.source %></h3>
<p><%= @fandom.description %></p>

<h3>Comments:</h3>
<ul class="comments">
  <% @fandom.comments.each do |a| %>
  <li>
  <%= a.content %> <br>
  -<%= a.user.name %>
  </li>
  <% end %>
</ul>

  <%= form_for [@fandom, @comment] do |a| %><br>
    <%= a.text_area :content, placeholder: 'Comments', id: 'comment-space' %><br>
    <%= a.submit %>
  <% end %>



<div class="guide">
<%= link_to('Edit', edit_fandom_path(params[:id]), class: "btn btn-primary") %>

<% if current_user.id === 2 %>
<%= link_to('Delete', @fandom, method: :delete, data: {confirm: 'Are you certain?'}, class: "btn btn-danger") %>
<% end %>

<% if current_user.fandoms.include? @fandom %>
<%= link_to('Unfavorite', unfavorite_path, class: 'btn btn-warning') %>
<% else %>
<%= link_to('Favorite', favorite_path(@fandom), class: 'btn btn-success') %>
<% end %>
<%= link_to('Back', fandoms_path, class: 'btn btn-default') %>
</div>

app/views/fandom/update.html.erb
<h1>Fandom#update</h1>
<p>Find me in app/views/fandom/update.html.erb</p>

app/views/front_page/index.html.erb
<h1 class="opening">Welcome to FanLife!</h1>
<p class="intro">This is a website dedicated to all the various fandoms that exist out there.<br>
Feel free to comment, favorite and edit all of the various fandoms that exist on our site,<br>
and if your favorite isn't there, feel free to add it on. <br>
All we ask is that you be respectful when posting, and please, <strong>don't hate on the fandoms you dislike!</strong></p>

<div class="start">
<%= link_to('Sign In', login_path) %>
<%= link_to('New User', new_user_path) %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'FanLife', root_path, {class: 'navbar-brand'} %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in %>
        <li><%= link_to user_path(current_user) do %>
    <span class="glyphicon glyphicon-user"></span>
    <%= current_user.name %>
  <% end %></li>
        <li><%= link_to('Check out the Fandoms', fandoms_path) %></li>
        <li><%= link_to('logout', logout_path, method: "delete", data: {confirm: 'Are you sure?'})%></li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanLife</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      	    <%= notice %>
	  <% end %>

	  <% if alert %>
      	    <%= alert %>
	  <% end %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<h1>Edit</h1>
<%= form_for @user, url:edit_user_path do |u| %>
<%= u.text_field :name, placeholder: 'Name' %>
<%= u.text_area :bio, placeholder: 'Bio' %>

<div class="images"> Profile Image
<%= u.file_field :user_image %>
</div>
<%= u.submit class: 'btn btn-success' %>
<% end %>

app/views/user/index.html.erb
<h1><%= @user.name %></h1>

<p><%= @user.bio %></p>

<%= link_to('Edit', edit_user_path) %>
<%= link_to('Logout', logout_path) %>

app/views/user/new.html.erb
<h1>Create an Account</h1>

<%= form_for @user do |f| %>
<div>
  <%= f.text_field :name, placeholder: "Name" %>
</div>

<div>
  <%= f.email_field :email, placeholder: "Email" %>
</div>

<div>
  <%= f.password_field :password, placeholder: "Password" %>
</div>

<div>
  <%= f.text_area :bio, placeholder: 'Bio', class: 'form-control' %>
</div>
<div class="images">
  Profile Picture
  <%= f.file_field :user_image %>
</div>
<%= f.submit 'Create Account', class: 'btn btn-success' %>
<% end  %>
<div class= "back">
<%= link_to('Go Back', root_path, class: 'btn btn-info') %>
</div>

app/views/user/show.html.erb
<h1><%= @user.name %></h1>
<%= image_tag(@user.user_image.url(:medium), class: "profile")  %>
<h3 class="h3">Bio</h3>
<p id="bio"><%= @user.bio %></p>


<h3 class="h3">Favorites</h3>
<ul class="favs">
  <% @user.fandoms.each do |f| %>
  <li> <%= link_to(f.title, fandom_path(f.id)) %> </li>
  <% end %>
</ul>
<div class="tools">
<%= link_to('Edit Your Page', edit_user_path, class: 'btn btn-warning') %> <br>
<%= link_to('Delete Your Account', @user, method: :delete, data: {confirm: 'Are you certain?'}, class: "btn btn-danger") %>
</div>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>